services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: information
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: my_postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: user_management
      DATABASE_USER: root
      DATABASE_PASSWORD: information
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: ["sh", "-c", "npm run migration:run && npm run start:dev"]

volumes:
  postgres_data:
